services:
  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/lib/rabbitmq/
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - hr-net

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - hr-net

  postgresdb:
    image: postgres:15.7
    restart: unless-stopped
    container_name: postgresql-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pedidos-api
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hr-net

  pgadmin-docker:
    image: dpage/pgadmin4
    container_name: ms-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: me@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5050:80
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    networks:
      - hr-net

volumes:
  postgres_data:
  rabbitmq_data:
  rabbitmq_log:

# ======================================================================================================================
# REDE
# ======================================================================================================================
networks:
  hr-net:
    driver: bridge